"""added read property to dm

Revision ID: e8d2078c146b
Revises: 567096d8589e
Create Date: 2021-05-28 12:41:54.690180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d2078c146b'
down_revision = '567096d8589e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_messages', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_messages', 'read')
    # ### end Alembic commands ###
