"""Added foreign key for referencing columns

Revision ID: 3af90bf403c5
Revises: 7e16d8ba61e8
Create Date: 2021-05-24 12:28:09.566170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af90bf403c5'
down_revision = '7e16d8ba61e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'channel_messages', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key(None, 'channel_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'channels', 'servers', ['server_id'], ['id'])
    op.create_foreign_key(None, 'private_messages', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'private_messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'servers', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channel_messages', type_='foreignkey')
    op.drop_constraint(None, 'channel_messages', type_='foreignkey')
    # ### end Alembic commands ###
