"""Added conversation table

Revision ID: 182858d130d4
Revises: 40f8e060501b
Create Date: 2021-05-25 18:38:18.435667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182858d130d4'
down_revision = '40f8e060501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('private_messages', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'private_messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_column('private_messages', 'conversation_id')
    op.drop_table('conversations')
    # ### end Alembic commands ###
